---
- hosts: localhost
  roles:
    - role: elliotweiser.osx-command-line-tools
  tasks:
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/install_zprezto.yml
    - import_tasks: tasks/setup_configs.yml
    - name: Install VSCode extensions
      shell: code-insiders --install-extension {{ item }}
      with_items:
        - vscodevim.vim
        - ms-vscode.cpptools
        - twxs.cmake
        - ms-vscode.cmake-tools
        - ms-vscode-remote.remote-ssh
