#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# git aliases (require my .gitconfig)
alias g='git'
alias gp='g p'
alias gl='g l'
alias s='g s'
alias d='g d'
alias gc='g c'

# OSX aliases
alias pp="open -a Preview"
alias f="open -a Finder ."

cdf() {
    target=`osascript -e 'tell application "Finder" to if (count of Finder windows) > 0 then get POSIX path of (target of front Finder window as text)'`
    if [ "$target" != "" ]; then
        cd "$target"; pwd
    else
        echo 'No Finder window found' >&2
    fi
}


# jobs aliases
alias ff=fg
alias gf=fg

alias .="cd .."

alias c='clear'
alias l='ls -CF'
alias ll='ls -lh'
alias la='ls -a'
alias lsa='ls -ld .*'

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/beckingsale1/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/beckingsale1/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/beckingsale1/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/beckingsale1/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

